name: OSCAL CI/CD
on:
  push:
    branches:
      - main
      - develop
      - "feature-*"
      - "release-*"
  pull_request:
    branches:
      - main
      - develop
      - "feature-*"
      - "release-*"
  workflow_dispatch:
jobs:
  checks:
    name: Status Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: "build/.nvmrc"
          cache: "npm"
          cache-dependency-path: "build/package-lock.json"
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - name: Run all pipelines
        run: |
          make --keep-going all
        working-directory: build
